### ISSUE TITLE
Listing of all sessions doesn't show captioning markers

### ISSUE THREAD

**Issue by benlk** [OpenNews/srccon-power#32]
At https://power.srccon.org/schedule/#_show-all :

<img width="1038" alt="screen shot 2018-12-14 at 3 31 40 pm" src="https://user-images.githubusercontent.com/1754187/50026021-714f8380-ffb5-11e8-8062-edcafebb0196.png">

No session is shown in the list of all sessions as having captions or transcripts; the closed-captioning icon is not visible.

**Comment by ryanpitts** [comment]
Yep! That's intentional—we didn't provide live transcripts of any of the breakout sessions at this event, just the talks. We'll connect with facilitators later on to see about editing/releasing the six sessions where transcription was present, but at this event we decided to go with post-publishing for those.

**Comment by benlk** [comment]
Oh, I see. I thought that the main talks were included in the list of all talks, but they're not there. 👍
